[book]
title = "VSETH-Rechtssammlung"
author = ["Verband der Studierenden an der ETH Zürich"]
description = "Die Rechtssammlung des VSETH."
src = ""
lang = "de"

[output.html]
default-theme = "light"
mathjax-support = false
no-section-label = true
git-repository-url = "https://gitlab.ethz.ch/vseth/0100-Reglemente/reglemente"
git-repository-icon = "fa-gitlab"

[output.html.print]
enable = false

[output.html.fold]
enable = true

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = false  # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search
