name: Build files
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make build-docker
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdfs
      path: |
          out/pdf/*.pdf
    - name: Download the artifact
      uses: actions/download-artifact@v4
      with:
        name: pdfs
    